import React, { type ReactNode } from "react";
import type { FlatListProps, ImageSourcePropType, ImageStyle, ModalProps, StyleProp, ViewStyle } from "react-native";
import CountryFilter, { type CountryFilterProps } from "./CountryFilter";
import { FlagButton } from "./FlagButton";
import { type Country, type CountryCode, type Region, type Subregion } from "./types";
export type CountryPickerProps = {
    allowFontScaling?: boolean;
    countryCode?: CountryCode;
    region?: Region;
    subregion?: Subregion;
    countryCodes?: CountryCode[];
    excludeCountries?: CountryCode[];
    preferredCountries?: CountryCode[];
    modalProps?: ModalProps;
    filterProps?: CountryFilterProps;
    flatListProps?: FlatListProps<Country>;
    withEmoji?: boolean;
    withCountryNameButton?: boolean;
    withCurrencyButton?: boolean;
    withCallingCodeButton?: boolean;
    withFlagButton?: boolean;
    withCloseButton?: boolean;
    withFilter?: boolean;
    withAlphaFilter?: boolean;
    withCallingCode?: boolean;
    withCurrency?: boolean;
    withFlag?: boolean;
    withModal?: boolean;
    disableNativeModal?: boolean;
    visible?: boolean;
    placeholder?: string;
    containerButtonStyle?: StyleProp<ViewStyle>;
    closeButtonImage?: ImageSourcePropType;
    closeButtonStyle?: StyleProp<ViewStyle>;
    closeButtonImageStyle?: StyleProp<ImageStyle>;
    renderFlagButton?(props: React.ComponentProps<typeof FlagButton>): ReactNode;
    renderCountryFilter?(props: React.ComponentProps<typeof CountryFilter>): ReactNode;
    onSelect?(country: Country): void;
    onOpen?(): void;
    onClose?(): void;
};
declare const CountryPicker: React.FC<CountryPickerProps>;
export default CountryPicker;
//# sourceMappingURL=CountryPicker.d.ts.map